[2022-06-25 09:13:58,677] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: analyze_json_data.processParsedData 2022-06-25T09:11:40.779593+00:00 [queued]>
[2022-06-25 09:13:58,689] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: analyze_json_data.processParsedData 2022-06-25T09:11:40.779593+00:00 [queued]>
[2022-06-25 09:13:58,689] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-06-25 09:13:58,689] {taskinstance.py:1043} INFO - Starting attempt 4 of 4
[2022-06-25 09:13:58,689] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-06-25 09:13:58,696] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): processParsedData> on 2022-06-25T09:11:40.779593+00:00
[2022-06-25 09:13:58,699] {standard_task_runner.py:52} INFO - Started process 2241 to run task
[2022-06-25 09:13:58,701] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'analyze_json_data', 'processParsedData', '2022-06-25T09:11:40.779593+00:00', '--job-id', '362', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dagRun.py', '--cfg-path', '/tmp/tmp_yf5_kx0', '--error-file', '/tmp/tmp6_3prpng']
[2022-06-25 09:13:58,703] {standard_task_runner.py:77} INFO - Job 362: Subtask processParsedData
[2022-06-25 09:13:58,733] {logging_mixin.py:104} INFO - Running <TaskInstance: analyze_json_data.processParsedData 2022-06-25T09:11:40.779593+00:00 [running]> on host bb303642214a
[2022-06-25 09:13:58,761] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Renato_Otescu
AIRFLOW_CTX_DAG_ID=analyze_json_data
AIRFLOW_CTX_TASK_ID=processParsedData
AIRFLOW_CTX_EXECUTION_DATE=2022-06-25T09:11:40.779593+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-25T09:11:40.779593+00:00
[2022-06-25 09:13:58,761] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-06-25 09:13:58,762] {bash.py:158} INFO - Running command: python /opt/airflow/sparkFiles/sparkProcess.py
[2022-06-25 09:13:58,770] {bash.py:169} INFO - Output:
[2022-06-25 09:13:59,784] {bash.py:173} INFO - WARNING: An illegal reflective access operation has occurred
[2022-06-25 09:13:59,784] {bash.py:173} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/airflow/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2022-06-25 09:13:59,784] {bash.py:173} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2022-06-25 09:13:59,784] {bash.py:173} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2022-06-25 09:13:59,784] {bash.py:173} INFO - WARNING: All illegal access operations will be denied in a future release
[2022-06-25 09:13:59,980] {bash.py:173} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2022-06-25 09:13:59,980] {bash.py:173} INFO - Setting default log level to "WARN".
[2022-06-25 09:13:59,980] {bash.py:173} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2022-06-25 09:14:00,180] {bash.py:173} INFO - 22/06/25 09:14:00 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2022-06-25 09:14:01,649] {bash.py:173} INFO - /home/airflow/.local/lib/python3.6/site-packages/pyspark/context.py:238: FutureWarning: Python 3.6 support is deprecated in Spark 3.2.
[2022-06-25 09:14:01,649] {bash.py:173} INFO -   FutureWarning
[2022-06-25 09:14:01,655] {bash.py:173} INFO - Traceback (most recent call last):
[2022-06-25 09:14:01,655] {bash.py:173} INFO -   File "/opt/airflow/sparkFiles/sparkProcess.py", line 22, in <module>
[2022-06-25 09:14:01,655] {bash.py:173} INFO -     ignoreTrailingWhiteSpace=True)
[2022-06-25 09:14:01,655] {bash.py:173} INFO -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/readwriter.py", line 410, in csv
[2022-06-25 09:14:01,655] {bash.py:173} INFO -     return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2022-06-25 09:14:01,655] {bash.py:173} INFO -   File "/home/airflow/.local/lib/python3.6/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2022-06-25 09:14:01,655] {bash.py:173} INFO -     answer, self.gateway_client, self.target_id, self.name)
[2022-06-25 09:14:01,655] {bash.py:173} INFO -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/utils.py", line 117, in deco
[2022-06-25 09:14:01,655] {bash.py:173} INFO -     raise converted from None
[2022-06-25 09:14:01,655] {bash.py:173} INFO - pyspark.sql.utils.AnalysisException: Path does not exist: file:/opt/airflow/sparkFiles/parsedData.csv
[2022-06-25 09:14:02,067] {bash.py:177} INFO - Command exited with return code 1
[2022-06-25 09:14:02,075] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-06-25 09:14:02,076] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=analyze_json_data, task_id=processParsedData, execution_date=20220625T091140, start_date=20220625T091358, end_date=20220625T091402
[2022-06-25 09:14:02,119] {local_task_job.py:146} INFO - Task exited with return code 1
